apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-ogsoft
  namespace: argocd
spec:
  destination:
    namespace: hello-ogsoft
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitlab.sikademo.com/ondrejsika/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hello-ogsoft
      values: |
        replicas: 4
        host: k8s.sikademo.com
        image: sikalabs/hello-world-server:ogsoft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
