apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web2
  namespace: argocd
spec:
  destination:
    namespace: web2
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitlab.sikademo.com/ondrejsika/web2.git
    targetRevision: v0.1.0
    path: ./kubernetes/charts/web2
    helm:
      releaseName: web2
      values: |
        image: registry.sikademo.com/ondrejsika/web2:master-737e4955-12
        host: web2.k8s.sikademo.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
