apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.sikalabs.iohttps://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.2.1
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          service:
            type: ClusterIP
          ingressClassResource:
            default: true
          kind: DaemonSet
          hostPort:
            enabled: true
          metrics:
            enabled: true
        defaultBackend:
          enabled: true
          image:
            registry: docker.io
            image: sikalabs/hello-world-server
            tag: ondrejsika
          extraEnvs:
            - name: TEXT
              value: "ogsoft-k8s-dev"
          port: 8000
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
