apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vaultwarden
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/guerzon/vaultwarden.git
    targetRevision: HEAD
    path: .
    helm:
      releaseName: vaultwarden
      values: |
        ingress:
          enabled: true
          hostname: vaultwarden.k8s-dev.sikademo.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
