apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd
spec:
  destination:
    namespace: web
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: ./charts/one-image
    helm:
      releaseName: web
      values: |
        host: web.k8s-dev.sikademo.com
        image: registry.sikademo.com/ondrejsika/web:main-3c86d0d7-7
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
