apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web2
  namespace: argocd
spec:
  destination:
    namespace: web2
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitlab.sikademo.com/ondrejsika/web2.git
    targetRevision: HEAD
    path: ./kubernetes/charts/web2
    helm:
      releaseName: web2
      values: |
        image: registry.sikademo.com/ondrejsika/web2:master-737e4955-12
        host: web2.k8s-dev.sikademo.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-web2
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  project: default
  type: git
  url: https://gitlab.sikademo.com/ondrejsika/web2.git
  username: ondrejsika
  password: asdfasdf
